server:
  port: 8081

game:
  player:
    start-location-id: city_square
    respawn-location-id: city_tavern
    start-gold: 50
    death-gold-penalty-percent: 20
    start-items:
      - template: "Длинный меч"
        amount: 1
      - template: "Малое зелье лечения"
        amount: 2
      - template: "Припасы"
        amount: 5

spring:
  profiles:
    default: local
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
