server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/dnd_tenebres
    username: postgres
    password: "31415926535"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml